### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [ZationServer/zation#1]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/ZationServer/zation/blob/master/package.json#L51

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by LucaCode** [comment]
Thanks for the note.
I removed `fs` from the dependencies.
